// <auto-generated />
using System;
using MediaHub.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediaHub.EntityFramework.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActorMovieInfo", b =>
                {
                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ActorId", "MovieInfoId");

                    b.HasIndex("MovieInfoId");

                    b.ToTable("ActorMovieInfo");
                });

            modelBuilder.Entity("AnimeStudioAnime", b =>
                {
                    b.Property<Guid>("AnimeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnimeStudioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AnimeId", "AnimeStudioId");

                    b.HasIndex("AnimeStudioId");

                    b.ToTable("AnimeStudioAnime");
                });

            modelBuilder.Entity("DirectorMovieInfo", b =>
                {
                    b.Property<Guid>("DirectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DirectorId", "MovieInfoId");

                    b.HasIndex("MovieInfoId");

                    b.ToTable("DirectorMovieInfo");
                });

            modelBuilder.Entity("GameDeveloperGame", b =>
                {
                    b.Property<Guid>("GameDeveloperId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameDeveloperId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("GameDeveloperGame");
                });

            modelBuilder.Entity("GamePlatformGame", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GamePlatformId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameId", "GamePlatformId");

                    b.HasIndex("GamePlatformId");

                    b.ToTable("GamePlatformGame");
                });

            modelBuilder.Entity("GamePublisherGame", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GamePublisherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameId", "GamePublisherId");

                    b.HasIndex("GamePublisherId");

                    b.ToTable("GamePublisherGame");
                });

            modelBuilder.Entity("GameTagGame", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameTagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameId", "GameTagId");

                    b.HasIndex("GameTagId");

                    b.ToTable("GameTagGame");
                });

            modelBuilder.Entity("MangaAuthorManga", b =>
                {
                    b.Property<Guid>("MangaAuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MangaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MangaAuthorId", "MangaId");

                    b.HasIndex("MangaId");

                    b.ToTable("MangaAuthorManga");
                });

            modelBuilder.Entity("MediaContentGenre", b =>
                {
                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MediaContentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GenreId", "MediaContentId");

                    b.HasIndex("MediaContentId");

                    b.ToTable("MediaContentGenre");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.Actor", b =>
                {
                    b.Property<Guid>("ActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ActorId");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.Anime", b =>
                {
                    b.Property<Guid>("AnimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MediaContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumberOfEpisodes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Rank")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AnimeId");

                    b.HasIndex("MediaContentId")
                        .IsUnique();

                    b.ToTable("Animes");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.AnimeStudio", b =>
                {
                    b.Property<Guid>("AnimeStudioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AnimeStudioId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AnimeStudios");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.CollectionUserRole", b =>
                {
                    b.Property<Guid>("CollectionUserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CollectionUserRoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CollectionUserRoles");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.ContentStatus", b =>
                {
                    b.Property<Guid>("ContentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ContentStatusId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ContentStatuses");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.Director", b =>
                {
                    b.Property<Guid>("DirectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DirectorId");

                    b.ToTable("Directors");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.Evaluation", b =>
                {
                    b.Property<Guid>("EvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EvaluationId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.Film", b =>
                {
                    b.Property<Guid>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MediaContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FilmId");

                    b.HasIndex("MediaContentId")
                        .IsUnique();

                    b.HasIndex("MovieInfoId")
                        .IsUnique();

                    b.ToTable("Films");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.Game", b =>
                {
                    b.Property<Guid>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("EsrbRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<Guid>("MediaContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("MetacriticRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<double>("PlaytimeHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.HasKey("GameId");

                    b.HasIndex("MediaContentId")
                        .IsUnique();

                    b.ToTable("Games");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.GameDeveloper", b =>
                {
                    b.Property<Guid>("GameDeveloperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GameDeveloperId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GameDevelopers");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.GamePlatform", b =>
                {
                    b.Property<Guid>("GamePlatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GamePlatformId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GamePlatforms");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.GamePublisher", b =>
                {
                    b.Property<Guid>("GamePublisherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GamePublisherId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GamePublishers");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.GameTag", b =>
                {
                    b.Property<Guid>("GameTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GameTagId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GameTags");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.Genre", b =>
                {
                    b.Property<Guid>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GenreId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.GenreEvaluation", b =>
                {
                    b.Property<Guid>("GenreEvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<Guid>("RecommendationCollectionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GenreEvaluationId");

                    b.HasIndex("GenreId");

                    b.HasIndex("RecommendationCollectionId");

                    b.ToTable("GenreEvaluations");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.Manga", b =>
                {
                    b.Property<Guid>("MangaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MediaContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumberOfChapters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("NumberOfVolumes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Rank")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MangaId");

                    b.HasIndex("MediaContentId")
                        .IsUnique();

                    b.ToTable("Mangas");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.MangaAuthor", b =>
                {
                    b.Property<Guid>("MangaAuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MangaAuthorId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MangaAuthors");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.MediaContent", b =>
                {
                    b.Property<Guid>("MediaContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainPictureLink")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("MediaContentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MediaContentId");

                    b.HasIndex("MediaContentTypeId");

                    b.ToTable("MediaContents");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.MediaContentPicture", b =>
                {
                    b.Property<Guid>("PictureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MediaContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PictureLink")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("PictureId");

                    b.HasIndex("MediaContentId");

                    b.ToTable("MediaContentPictures");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.MediaContentType", b =>
                {
                    b.Property<Guid>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MediaContentTypes");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.MediaInteractionStatus", b =>
                {
                    b.Property<Guid>("MediaInteractionStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContentStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EvaluationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MediaContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecommendationCollectionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MediaInteractionStatusId");

                    b.HasIndex("ContentStatusId");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("MediaContentId");

                    b.HasIndex("RecommendationCollectionId");

                    b.ToTable("MediaInteractionStatuses");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.MovieInfo", b =>
                {
                    b.Property<Guid>("MovieInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DurationInMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.HasKey("MovieInfoId");

                    b.ToTable("MovieInfos");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.RecommendationCollection", b =>
                {
                    b.Property<Guid>("CollectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CollectionId");

                    b.HasIndex("CreatorUserId");

                    b.ToTable("RecommendationCollections");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.RecommendationCollectionUserAccess", b =>
                {
                    b.Property<Guid>("UserAccessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CollectionUserRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecommendationCollectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserAccessId");

                    b.HasIndex("CollectionUserRoleId");

                    b.HasIndex("RecommendationCollectionId");

                    b.HasIndex("UserId");

                    b.ToTable("RecommendationCollectionUserAccesses");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.Serial", b =>
                {
                    b.Property<Guid>("SerialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MediaContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumberOfEpisodes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("NumberOfSeasons")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("SerialId");

                    b.HasIndex("MediaContentId")
                        .IsUnique();

                    b.HasIndex("MovieInfoId")
                        .IsUnique();

                    b.ToTable("Serials");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MediaHub.Models.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ActorMovieInfo", b =>
                {
                    b.HasOne("MediaHub.Models.Entities.Actor", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaHub.Models.Entities.MovieInfo", null)
                        .WithMany()
                        .HasForeignKey("MovieInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnimeStudioAnime", b =>
                {
                    b.HasOne("MediaHub.Models.Entities.Anime", null)
                        .WithMany()
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaHub.Models.Entities.AnimeStudio", null)
                        .WithMany()
                        .HasForeignKey("AnimeStudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DirectorMovieInfo", b =>
                {
                    b.HasOne("MediaHub.Models.Entities.Director", null)
                        .WithMany()
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaHub.Models.Entities.MovieInfo", null)
                        .WithMany()
                        .HasForeignKey("MovieInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameDeveloperGame", b =>
                {
                    b.HasOne("MediaHub.Models.Entities.GameDeveloper", null)
                        .WithMany()
                        .HasForeignKey("GameDeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaHub.Models.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamePlatformGame", b =>
                {
                    b.HasOne("MediaHub.Models.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaHub.Models.Entities.GamePlatform", null)
                        .WithMany()
                        .HasForeignKey("GamePlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamePublisherGame", b =>
                {
                    b.HasOne("MediaHub.Models.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaHub.Models.Entities.GamePublisher", null)
                        .WithMany()
                        .HasForeignKey("GamePublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameTagGame", b =>
                {
                    b.HasOne("MediaHub.Models.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaHub.Models.Entities.GameTag", null)
                        .WithMany()
                        .HasForeignKey("GameTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MangaAuthorManga", b =>
                {
                    b.HasOne("MediaHub.Models.Entities.MangaAuthor", null)
                        .WithMany()
                        .HasForeignKey("MangaAuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaHub.Models.Entities.Manga", null)
                        .WithMany()
                        .HasForeignKey("MangaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediaContentGenre", b =>
                {
                    b.HasOne("MediaHub.Models.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaHub.Models.Entities.MediaContent", null)
                        .WithMany()
                        .HasForeignKey("MediaContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediaHub.Models.Entities.Anime", b =>
                {
                    b.HasOne("MediaHub.Models.Entities.MediaContent", "MediaContent")
                        .WithOne("Anime")
                        .HasForeignKey("MediaHub.Models.Entities.Anime", "MediaContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaContent");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.Film", b =>
                {
                    b.HasOne("MediaHub.Models.Entities.MediaContent", "MediaContent")
                        .WithOne("Film")
                        .HasForeignKey("MediaHub.Models.Entities.Film", "MediaContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaHub.Models.Entities.MovieInfo", "MovieInfo")
                        .WithOne("Film")
                        .HasForeignKey("MediaHub.Models.Entities.Film", "MovieInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaContent");

                    b.Navigation("MovieInfo");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.Game", b =>
                {
                    b.HasOne("MediaHub.Models.Entities.MediaContent", "MediaContent")
                        .WithOne("Game")
                        .HasForeignKey("MediaHub.Models.Entities.Game", "MediaContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaContent");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.GenreEvaluation", b =>
                {
                    b.HasOne("MediaHub.Models.Entities.Genre", "Genre")
                        .WithMany("GenreEvaluations")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaHub.Models.Entities.RecommendationCollection", "RecommendationCollection")
                        .WithMany("GenreEvaluations")
                        .HasForeignKey("RecommendationCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("RecommendationCollection");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.Manga", b =>
                {
                    b.HasOne("MediaHub.Models.Entities.MediaContent", "MediaContent")
                        .WithOne("Manga")
                        .HasForeignKey("MediaHub.Models.Entities.Manga", "MediaContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaContent");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.MediaContent", b =>
                {
                    b.HasOne("MediaHub.Models.Entities.MediaContentType", "MediaContentType")
                        .WithMany("MediaContents")
                        .HasForeignKey("MediaContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MediaContentType");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.MediaContentPicture", b =>
                {
                    b.HasOne("MediaHub.Models.Entities.MediaContent", "MediaContent")
                        .WithMany("MediaContentPictures")
                        .HasForeignKey("MediaContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaContent");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.MediaInteractionStatus", b =>
                {
                    b.HasOne("MediaHub.Models.Entities.ContentStatus", "ContentStatus")
                        .WithMany("MediaInteractionStatuses")
                        .HasForeignKey("ContentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediaHub.Models.Entities.Evaluation", "Evaluation")
                        .WithMany("MediaInteractionStatuses")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MediaHub.Models.Entities.MediaContent", "MediaContent")
                        .WithMany("MediaInteractionStatuses")
                        .HasForeignKey("MediaContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaHub.Models.Entities.RecommendationCollection", "RecommendationCollection")
                        .WithMany("MediaInteractionStatus")
                        .HasForeignKey("RecommendationCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentStatus");

                    b.Navigation("Evaluation");

                    b.Navigation("MediaContent");

                    b.Navigation("RecommendationCollection");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.RecommendationCollection", b =>
                {
                    b.HasOne("MediaHub.Models.Entities.User", "CreatorUser")
                        .WithMany("RecommendationCollections")
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatorUser");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.RecommendationCollectionUserAccess", b =>
                {
                    b.HasOne("MediaHub.Models.Entities.CollectionUserRole", "CollectionUserRole")
                        .WithMany("RecommendationCollectionUserAccesses")
                        .HasForeignKey("CollectionUserRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediaHub.Models.Entities.RecommendationCollection", "RecommendationCollection")
                        .WithMany("RecommendationCollectionUserAccesses")
                        .HasForeignKey("RecommendationCollectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediaHub.Models.Entities.User", "User")
                        .WithMany("RecommendationCollectionUserAccess")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CollectionUserRole");

                    b.Navigation("RecommendationCollection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.Serial", b =>
                {
                    b.HasOne("MediaHub.Models.Entities.MediaContent", "MediaContent")
                        .WithOne("Serial")
                        .HasForeignKey("MediaHub.Models.Entities.Serial", "MediaContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaHub.Models.Entities.MovieInfo", "MovieInfo")
                        .WithOne("Serial")
                        .HasForeignKey("MediaHub.Models.Entities.Serial", "MovieInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaContent");

                    b.Navigation("MovieInfo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("MediaHub.Models.Entities.UserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MediaHub.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MediaHub.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("MediaHub.Models.Entities.UserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaHub.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MediaHub.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediaHub.Models.Entities.CollectionUserRole", b =>
                {
                    b.Navigation("RecommendationCollectionUserAccesses");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.ContentStatus", b =>
                {
                    b.Navigation("MediaInteractionStatuses");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.Evaluation", b =>
                {
                    b.Navigation("MediaInteractionStatuses");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.Genre", b =>
                {
                    b.Navigation("GenreEvaluations");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.MediaContent", b =>
                {
                    b.Navigation("Anime");

                    b.Navigation("Film");

                    b.Navigation("Game");

                    b.Navigation("Manga");

                    b.Navigation("MediaContentPictures");

                    b.Navigation("MediaInteractionStatuses");

                    b.Navigation("Serial");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.MediaContentType", b =>
                {
                    b.Navigation("MediaContents");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.MovieInfo", b =>
                {
                    b.Navigation("Film");

                    b.Navigation("Serial");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.RecommendationCollection", b =>
                {
                    b.Navigation("GenreEvaluations");

                    b.Navigation("MediaInteractionStatus");

                    b.Navigation("RecommendationCollectionUserAccesses");
                });

            modelBuilder.Entity("MediaHub.Models.Entities.User", b =>
                {
                    b.Navigation("RecommendationCollectionUserAccess");

                    b.Navigation("RecommendationCollections");
                });
#pragma warning restore 612, 618
        }
    }
}
